[2024-02-22T22:58:44.898+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.print_result_task manual__2024-02-22T22:58:41.155621+00:00 [queued]>
[2024-02-22T22:58:44.904+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.print_result_task manual__2024-02-22T22:58:41.155621+00:00 [queued]>
[2024-02-22T22:58:44.904+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-22T22:58:44.905+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-22T22:58:44.905+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-22T22:58:44.914+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): print_result_task> on 2024-02-22 22:58:41.155621+00:00
[2024-02-22T22:58:44.918+0000] {standard_task_runner.py:55} INFO - Started process 142 to run task
[2024-02-22T22:58:44.920+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bancodedados', 'print_result_task', 'manual__2024-02-22T22:58:41.155621+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/bancodedados.py', '--cfg-path', '/tmp/tmp40svc78c']
[2024-02-22T22:58:44.920+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask print_result_task
[2024-02-22T22:58:44.957+0000] {task_command.py:388} INFO - Running <TaskInstance: bancodedados.print_result_task manual__2024-02-22T22:58:41.155621+00:00 [running]> on host 476c18be81c0
[2024-02-22T22:58:44.997+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bancodedados
AIRFLOW_CTX_TASK_ID=print_result_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-22T22:58:41.155621+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-22T22:58:41.155621+00:00
[2024-02-22T22:58:44.998+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bancodedados.py", line 14, in print_result_task
    task_instance = var.xcom_pull(task_ids='query_data')
AttributeError: 'dict' object has no attribute 'xcom_pull'
[2024-02-22T22:58:45.002+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bancodedados, task_id=print_result_task, execution_date=20240222T225841, start_date=20240222T225844, end_date=20240222T225845
[2024-02-22T22:58:45.009+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task print_result_task ('dict' object has no attribute 'xcom_pull'; 142)
[2024-02-22T22:58:45.052+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-22T22:58:45.064+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
